### ISSUE TITLE
邮箱可配置项太少

### ISSUE THREAD

**Issue by hellotuitu** [JasonSi/hack_my_school#1]
应该增加的配置项至少应该有:
- 端口号
- 是否开启ssl(可默认为true或false,但是一定要可配置)

还有异常处理过于简介了,出错了至少应该把错误显示出来.

因为rm命令常年带上rf参数使用,导致我要重新配置很多东西,包括这个爬虫...
结果遇到一堆坑,邮件发送失败也不知道是啥错,还得去改代码.

**Comment by pujiaxun** [comment]
可能是我没做好开源的准备。。 SSL的配置踩了不少坑，求PR？

异常处理这个问题也是偷懒，因为不想直接crash，我遇到大部分的报错都是超时、网络错误之类的，我的第一目标是让他可持续自动爬，所以粗暴掩盖掉了。
